package main

import (
	"encoding/json"
	"fmt"
	"github.com/pjunak/addon-dnd-character-sheets/internal/character"
	"os"
	"reflect"
	"sort"
	"strings"
	"time"
)

func writeTypescript() {
	declarations := map[string]string{}
	var emit func(reflect.Type) string
	emit = func(t reflect.Type) string {
		if t.Kind() == reflect.Pointer {
			return emit(t.Elem())
		}
		if t == reflect.TypeOf(time.Time{}) {
			return "string"
		}
		if t == reflect.TypeOf(json.RawMessage{}) {
			return "unknown"
		}
		switch t.Kind() {
		case reflect.String:
			return "string"
		case reflect.Bool:
			return "boolean"
		case reflect.Int, reflect.Int64, reflect.Float64:
			return "number"
		case reflect.Slice:
			return "Array<" + emit(t.Elem()) + ">"
		case reflect.Map:
			return "Record<string, " + emit(t.Elem()) + ">"
		case reflect.Struct:
			name := t.Name()
			if _, ok := declarations[name]; ok {
				return name
			}
			declarations[name] = ""
			lines := []string{"export interface " + name + " {"}
			for i := 0; i < t.NumField(); i++ {
				field := t.Field(i)
				tags := strings.Split(field.Tag.Get("json"), ",")
				if tags[0] == "-" {
					continue
				}
				optional := ""
				if len(tags) > 1 {
					optional = "?"
				}
				lines = append(lines, fmt.Sprintf("  %s%s: %s;", tags[0], optional, emit(field.Type)))
			}
			lines = append(lines, "}")
			declarations[name] = strings.Join(lines, "\n")
			return name
		}
		return "unknown"
	}
	emit(reflect.TypeOf(character.Request{}))
	emit(reflect.TypeOf(character.Response{}))
	keys := []string{}
	for key := range declarations {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	output := "// Generated by go run ./cmd/character-contract. Do not edit.\n"
	for _, key := range keys {
		output += "\n" + declarations[key] + "\n"
	}
	if err := os.WriteFile("src/character-model.ts", []byte(output), 0644); err != nil {
		panic(err)
	}
}
