import { readFile, writeFile, readdir } from "node:fs/promises";
import ts from "typescript";
const catalogs: Record<string, Record<string, string>> = {};
for (const locale of ["en", "cs"]) {
  catalogs[locale] = JSON.parse(await readFile(new URL(`../locales/${locale}.json`, import.meta.url), "utf8")) as Record<string, string>;
  if (!Object.values(catalogs[locale]).every(value => typeof value === "string")) throw new Error(`Invalid ${locale} catalog.`);
}
if (JSON.stringify(Object.keys(catalogs["en"]!).sort()) !== JSON.stringify(Object.keys(catalogs["cs"]!).sort())) throw new Error("English and Czech catalogs must cover the same controls.");
for (const [key, value] of Object.entries(catalogs["cs"]!)) {
  const placeholders = (text: string): string => JSON.stringify([...text.matchAll(/\{\d+\}/gu)].map(match => match[0]).sort());
  if (placeholders(value) !== placeholders(catalogs["en"]![key]!)) throw new Error(`Translation changes placeholders: ${key}`);
}
const missing = new Set<string>();
for (const file of await readdir(new URL("../src/", import.meta.url))) {
  if (!file.startsWith("character-") || !file.endsWith(".ts") || file === "character-messages.ts") continue;
  const source = ts.createSourceFile(file, await readFile(new URL(`../src/${file}`, import.meta.url), "utf8"), ts.ScriptTarget.Latest, true);
  const visit = (node: ts.Node): void => {
    if (ts.isCallExpression(node) && (node.expression.getText(source) === "t" || node.expression.getText(source) === "this.#t") && node.arguments[0] && ts.isStringLiteral(node.arguments[0]) && !Object.hasOwn(catalogs["en"]!, node.arguments[0].text)) missing.add(node.arguments[0].text);
    ts.forEachChild(node, visit);
  };
  visit(source);
}
if (missing.size) throw new Error(`Missing UI translations: ${JSON.stringify([...missing])}`);
await writeFile(new URL("../src/character-messages.ts", import.meta.url), `// Generated by tools/build-locales.ts from the UI catalogs.\nexport const catalogs = ${JSON.stringify(catalogs, null, 2)} as const;\n`);
