// Generated by go run ./cmd/character-contract. Do not edit.

export interface Build {
  method: string;
  baseScores: Record<string, number>;
  rolls: Array<Roll>;
  species: string;
  lineage: string;
  background: string;
  levels: Array<Level>;
  subclasses: Record<string, string>;
  choices: Array<Choice>;
  spells: SpellDecisions;
}

export interface Choice {
  id: string;
  slot: number;
  value: unknown;
}

export interface Container {
  id: string;
  name: string;
}

export interface Difference {
  path: string;
  before: unknown;
  after: unknown;
}

export interface Effect {
  target: string;
  key?: string;
  mode: string;
  value: number;
}

export interface Evidence {
  reference: Reference;
  name: string;
  book?: string;
  hash: string;
  summary: string;
  facts: Record<string, unknown>;
  packageId?: string;
  packageGeneration?: string;
  contentRevision?: string;
}

export interface Explanation {
  label: string;
  formula: string;
  value: unknown;
  unit?: string;
  minimum?: number;
  maximum?: number;
  terms: Array<Term>;
  sources: Array<Reference>;
}

export interface Grant {
  id: string;
  name: string;
  reason: string;
  actorId: string;
  grantedAt: string;
  active: boolean;
  effectiveLevel: number;
  expiresAt?: string;
  itemId?: string;
  condition: string;
  feat?: Reference;
  effects: Array<Effect>;
  waivers: Array<string>;
}

export interface Inputs {
  build: Build;
  play: Play;
  grants: Array<Grant>;
  notes: string;
}

export interface Issue {
  id: string;
  target: string;
  message: string;
  severity: string;
  reference?: Reference;
}

export interface Item {
  id: string;
  containerId?: string;
  reference?: Reference;
  spellId?: string;
  name: string;
  quantity: number;
  location: string;
  attuned: boolean;
  acquisition: string;
  grantId?: string;
  notes: string;
}

export interface Level {
  id: string;
  classId: string;
  hitPoints?: number;
}

export interface Play {
  inspiration?: boolean;
  quickUse?: Array<string>;
  containers?: Array<Container>;
  rolls: Array<PlayRoll>;
  hp: number;
  temporaryHp: number;
  inventory: Array<Item>;
  currency: Record<string, number>;
  resourceUses: Record<string, number>;
  activeFeatures: Record<string, boolean>;
  preparedSpells: Record<string, Array<string>>;
  asOf: string;
}

export interface PlayRoll {
  origin?: string;
  id: string;
  resource: string;
  die: number;
  result: number;
  at: string;
}

export interface Projection {
  sheet: Record<string, unknown>;
  explanations: Record<string, Explanation>;
  evidence: Array<Evidence>;
  issues: Array<Issue>;
}

export interface Reference {
  kind: string;
  id: string;
}

export interface Request {
  contractVersion: string;
  key: string;
  expectedRevision?: number;
  operation?: string;
  operationId?: string;
  summary?: string;
  inputs?: Inputs;
  change?: Record<string, unknown>;
  grant?: Grant;
  grantId?: string;
  token?: string;
  adoptRules?: boolean;
  reauthorizeGrants?: boolean;
}

export interface Response {
  contractVersion: string;
  status: string;
  message: string;
  key: string;
  revision: number;
  actorId: string;
  role: string;
  state?: State;
  evaluation?: Result;
  policy?: Record<string, unknown>;
  changes?: Array<Difference>;
  token?: string;
  expiresAt?: string;
  rulesChanged: boolean;
}

export interface Result {
  contractVersion: string;
  inputs: Inputs;
  sheet: Record<string, unknown>;
  guidance: Record<string, unknown>;
  plan: Record<string, unknown>;
  spellOptions: Record<string, unknown>;
  explanations: Record<string, Explanation>;
  evidence: Array<Evidence>;
  issues: Array<Issue>;
  ready: boolean;
}

export interface Roll {
  origin?: string;
  id: string;
  ability: string;
  dice: Array<number>;
  kept: Array<number>;
}

export interface RulesContext {
  engineId: string;
  engineVersion: string;
  engineGeneration: string;
  identity: Record<string, unknown>;
}

export interface SpellAcquisition {
  origin?: string;
  id: string;
  classId: string;
  spellId: string;
  level: number;
  at: string;
  costGp: number;
  scrollId?: string;
}

export interface SpellDecisions {
  cantrips: Record<string, Array<string>>;
  spellbook: Record<string, Array<string>>;
  grantChoices: Record<string, Array<string>>;
  castingAbilities: Record<string, string>;
  swaps: Array<SpellSwap>;
  acquisitions: Array<SpellAcquisition>;
}

export interface SpellSwap {
  origin?: string;
  level: number;
  classLevel: number;
  classId: string;
  out: string;
  in: string;
}

export interface State {
  schemaVersion: string;
  inputs: Inputs;
  projection: Projection;
  rules: RulesContext;
  operationId: string;
}

export interface Term {
  label: string;
  value: unknown;
  source?: Reference;
  grantId?: string;
  status?: string;
}
